config/routes.rb
DclgStatsSelector::Engine.routes.draw do
  resources :selectors, except: [:index, :edit, :update] do
    member do
      get :download
      # get :create # so we can redirect here from the geo selector
    end

    resources :fragments, except: [:show, :index] do
      get :datasets, on: :collection
    end
  end
end

app/models/dclg_stats_selector/csv_builder.rb
require 'csv'

module DclgStatsSelector
  class CSVBuilder
    DEFAULT_HEADER_ROW_STRATEGIES = {
      dataset:          { display: :uri,   padding: :blank },
      measure_property: { display: :label, padding: :blank },
      dimension_value:  { display: :label, padding: :duplicate },
      blank:            { display: :none,  padding: :blank }
    }.freeze

    class << self
      # Helper method to make a new stats selector. Note the overloading
      # of the word "build" here - this method doesn't return a CSV!
      def build(metadata)
        new(
          metadata.merge(header_row_strategies: DEFAULT_HEADER_ROW_STRATEGIES)
        )
      end
    end

    def initialize(metadata_and_opts)
      @source_url = metadata_and_opts.fetch(:source_url)
      @timestamp  = metadata_and_opts.fetch(:timestamp)
      @site_name  = metadata_and_opts.fetch(:site_name)

      @header_row_strategies = metadata_and_opts.fetch(:header_row_strategies)

      @csv = CSV.new(String.new)
    end

    def document_header_started
      @csv << ["Generated by #{@site_name}", @timestamp]
      @csv << ["Source:", @source_url]
    end

    def document_header_finished
      @csv << []
    end

    def header_row(row, has_secondary_row_headings=false)
      padding = has_secondary_row_headings ? ['','','',''] : ['','']
      @csv << padding + row.inject([]) { |csv_row, cell|
        csv_row.concat(text_cells(cell))
      }
    end

    def table_row(row_description)
      row_values = [
        row_description.fetch(:row_uri),
        row_description.fetch(:row_label),
        *row_description.fetch(:values)
      ]
      if row_description[:secondary_row_uri]
        row_values = [row_description.fetch(:secondary_row_uri), row_description.fetch(:secondary_row_label)] + row_values
      end
      @csv << row_values
    end

    def to_csv
      @csv.string
    end

    private

    def text_cells(cell)
      cell_type_options = @header_row_strategies[cell.type] or
        raise ArgumentError.new("No header row strategy for #{cell.type.inspect}")
      cell_display_type = cell_type_options[:display] or
        raise ArgumentError.new("No :display option given for #{cell.type.inspect}")
      cell_padding_strategy = cell_type_options[:padding] or
        raise ArgumentError.new("No :padding option given for #{cell.type.inspect}")

      cell_text =
        case cell_display_type
        when :uri
          cell.uri
        when :label
          cell.label
        when :none
          ""
        else
          raise ArgumentError.new("Unknown cell display type #{cell_display_type.inspect}")
        end

      cells = []
      cells << cell_text

      padding_cells =
        case cell_padding_strategy
        when :blank
          [""] * (cell.width - 1)
        when :duplicate
          [cell_text] * (cell.width - 1)
        else
          raise ArgumentError.new("Unknown cell padding strategy #{cell_padding_strategy.inspect}")
        end

      cells.concat(padding_cells)
    end
  end
end

app/models/dclg_stats_selector/fragment.rb
module DclgStatsSelector
  class Fragment
    include Mongoid::Document
    include Mongoid::Attributes::Dynamic

    field :dataset_uri
    field :measure_property_uri
    field :dimensions, type: Hash

    embedded_in :selector

    # An opaque token that identifies fragments (relatively) uniquely
    # and is suitable for using in a CSS class name
    #
    # Note that this duplicates the logic in HeaderCell and TableCell
    # (The reason we need it here is because the Selector show template
    # iterates the fragments to generate the footer - otherwise we could
    # pass a code in when building the snapshot)
    def fragment_code
      self.dataset_uri.hash
    end

    def deep_copy
      Fragment.new(self.attributes)
    end

    def inform_observation_source(observation_source)
      observation_source.dataset_detected(
        dataset_uri:          dataset_uri,
        measure_property_uri: measure_property_uri,
        dimensions:           dimensions
      )
    end

    def inform_snapshot(snapshot)
      snapshot.dataset_detected(
        dataset_uri:          dataset_uri,
        measure_property_uri: measure_property_uri
      )

      each_dimension_bottom_up_with_level do |(dimension_uri, values), level|
        snapshot.dimension_detected(
          dimension_uri:  dimension_uri,
          column_width:   number_of_encompassed_dimension_values_at_level(level),
          column_uris:    values
        )
      end

      snapshot.dataset_completed
    end

    def inform_labeller(labeller)
      labellable_resource_uris.each do |resource_uri|
        labeller.resource_detected(resource_uri)
      end
    end

    def number_of_encompassed_dimension_values_at_level(level)
      if number_of_dimensions == 0
        0 # Special case as the main algorithm starts Enumerable#reduce with 1
      else
        volume_of_selected_cube / volume_at_level(level)
      end
    end

    # Only still public because of the show page
    def volume_of_selected_cube
      volume_at_level(bottom_level)
    end

    def dimensions=(dims)
      dims = dims.reduce({}) do |memo, (key, value)|
        key = key.gsub('.', '__')
        memo[key] = value
        memo
      end
      write_attribute(:dimensions, dims)
    end

    def dimensions
      dims = read_attribute(:dimensions)
      dims.reduce({}) do |memo, (key, value)|
        key = key.gsub('__', '.')
        memo[key] = value
        memo
      end
    end

    private

    # Candidate for the prize for "most specific enumeration method"
    def each_dimension_bottom_up_with_level(&block)
      # Watch out as there's no spec for the use of reverse here
      dimensions.map.with_index.to_a.reverse.each(&block)
    end

    def dimension_value_pairs
      dimensions.reduce([]) { |coords, (dimension_uri, dimension_values)|
        coords << dimension_values.map { |value| {dimension_uri => value} }
      }
    end

    def volume_at_level(level)
      dimensions.keys[0..level].reduce(1) { |volume, dimension|
        volume * dimensions[dimension].length
      }
    end

    def volume_at_level_above(level)
      if level == 0
        1
      else
        volume_at_level(level - 1)
      end
    end

    def bottom_level
      number_of_dimensions
    end

    def number_of_dimensions
      dimensions.length
    end

    def labellable_resource_uris
      [
        dataset_uri,
        measure_property_uri
      ].concat(
        dimensions.keys
      ).concat(
        dimensions.values
      ).flatten
    end
  end
end

app/models/dclg_stats_selector/labeller.rb
module DclgStatsSelector
  # A lazy, batching labeller for resources. It listens for
  # #resource_detected, and loads all resource labels from the
  # Tripod database when the first #label_for a resource is
  # requested.
  class Labeller
    def initialize
      @resource_uris = [ ]
    end

    def resource_detected(resource_uri)
      @resource_uris << resource_uri
    end

    def label_for(resource_uri)
      labels[resource_uri] || resource_uri
    end

    private

    def labels
      @labels ||= begin
        resources.reduce({ }) { |hash, resource|
          hash.merge!(resource.uri.to_s => resource.label)
        }
      end
    end

    def resources
      PublishMyData::Resource.find_by_sparql <<-SPARQL
        SELECT ?uri
        WHERE {
          VALUES ?uri { #{resource_uris_for_sparql.join(" ")} }
        }
      SPARQL
    end

    def resource_uris_for_sparql
      @resource_uris.map { |uri| "<#{uri}>" }
    end
  end
end

app/controllers/dclg_stats_selector/fragments_controller.rb
module DclgStatsSelector
  class FragmentsController < PublishMyData::ApplicationController
    before_filter :get_dataset, only:  [ :new, :create ]
    before_filter :get_selector, only: [ :datasets, :new, :create, :destroy ]
    before_filter :get_fragment, only: [ :destroy ]

    def datasets
      datasets = GeographyService.geographical_data_cubes(@selector.geography_type)
      
      default_tree = build_site_trees.select{ |t| t.is_default_tree? }.first
      @tree = filtered_tree(default_tree, datasets)

      respond_to do |format|
        format.html { render layout: false }
        format.js
      end
    end

    def new
      @dimensions = PublishMyData::DataCube::Cube.new(@dataset).dimension_objects
      @dimensions.reject! {|d| d.uri == 'http://opendatacommunities.org/def/ontology/geography/refArea'}

      respond_to do |format|
        format.js
      end
    end

    def create
      dimensions = dimensions_from_params(params[:dataset_dimensions])

      # The Data Cube spec permits multiple measures per observation:
      # http://www.w3.org/TR/vocab-data-cube/#dsd-mm-obs
      # PMD currently only supports one measure property in a cube,
      # so we currently just pick the first available. This sort of
      # policy shouldn't live in a controller, but we'd need to
      # restructure the code a lot to give it a proper home.
      measure_property_uri = ObservationSource.measure_property_uri(@dataset.uri)

      @selector.fragments.build(
        dataset_uri:          @dataset.uri.to_s,
        measure_property_uri: measure_property_uri,
        dimensions:           dimensions
      )

      if @selector.save
        redirect_to selector_path(@selector)
      end
    end

    def destroy
      @selector.fragments.delete(@fragment)

      if @selector.save
        redirect_to selector_path(@selector)
      end
    end

    private

    def get_dataset
      @dataset = PublishMyData::Dataset.find(params[:dataset_uri])
    end

    def get_selector
      @selector = Selector.find(params[:selector_id])
    end

    def get_fragment
      @fragment = @selector.fragments.find(params[:id])
    end

    def filtered_tree(tree, datasets)
      filtered_tree = tree.tree_node.dup
      # build an array of all nodes to be included in the filter
      filtered_nodes = datasets.reduce([]) do |memo, dataset|
        leaf = tree.find_node_with_uri(dataset.uri)
        if leaf
          nodes = leaf.parentage + [leaf]
          memo = memo | nodes
        end
        memo
      end
      filtered_tree.breadth_each do |node|
        node.remove_from_parent! unless filtered_nodes.include?(node)
      end
    end

    # Converts {dimension_uri => csv_dimension_value_data} to {dimension_uri => [dim_value_1, ...]}
    # and uses all dimension values for a dimension if none were provided
    def dimensions_from_params(dimension_params)
      dimension_params.reduce({}) do |dimensions, (dimension_uri, value_data)|
        dimension_values_provided = value_data.split(', ')

        dimension_values =
          if dimension_values_provided.present?
            dimension_values_provided
          else
            all_dimensions[dimension_uri]
          end

        dimensions.merge!(dimension_uri => dimension_values)
      end
    end

    def all_dimensions
      all_dimensions = params[:all_dataset_dimensions]
      all_dimensions.keys.reduce({}) do |dimensions_map, dimension_uri|
        dimensions_map[dimension_uri] = all_dimensions[dimension_uri].split(', ')
        dimensions_map
      end
    end
  end
end

app/controllers/dclg_stats_selector/selectors_controller.rb
module DclgStatsSelector
  class SelectorsController < PublishMyData::ApplicationController

    layout 'stats_selector'

    before_filter :get_selector, only: [ :show, :download ]
  #  before_filter :crumbs

    rescue_from GeographyService::TooManyGSSCodesError, with: :too_many_gss_codes
    rescue_from GeographyService::TooManyGSSCodeTypesError, with: :mixed_gss_codes

   # include PublishMyData::CrumbtrailRendering
    
    def new
    end

    def create
      (no_file_uploaded && return) unless params[:csv_upload]

      data = process_csv_upload(params[:csv_upload], { postcode: params[:postcode] })
      (invalid_upload && return) unless data

      @selector = Selector.create(
        geography_type:       data.fetch(:geography_type, 'http://opendatacommunities.org/def/geography#LSOA'),
        row_uris:             data.fetch(:gss_resource_uris),
        secondary_row_uris:   data.fetch(:secondary_resource_uris, nil)
      )

      redirect_to selector_path(@selector, imported: @selector.row_uris.count, not_imported: data.fetch(:non_gss_codes).join(','))
    end

    def show
      @snapshot = @selector.build_snapshot(row_limit: 10)

      if params[:imported]
        @imported_count = params[:imported].to_i
        @non_gss_codes = params[:not_imported].split(',')
      end
    end

    def download
      @selector = @selector.deep_copy
      snapshot = @selector.build_snapshot
      filename = "statistics"
      source_url = selector_url(@selector)
      output_builder = CSVBuilder.build(
        site_name:  PublishMyData.request_root,
        source_url: source_url,
        timestamp:  Time.now
      )
      snapshot.render(output_builder)

      response.headers['Content-Type'] = 'text/csv'
      response.headers['Content-Disposition'] = %'attachment; filename="#{filename}.csv"'
      render(text: output_builder.to_csv)
    end

    private

    def get_selector
      @selector = Selector.find(params[:id])
    end

    def process_csv_upload(upload, opts={})
      is_postcode_data = opts.fetch(:postcode, false)

      geography_service = GeographyService.new

      # The error handling used to live in the Selector, and I've preserved the
      # use of rescue_from for now, hence catching and raising an error within
      # the controller
      uri_candidates =
        begin
          CSV.read(upload.path).map{|a| a.first.to_s.strip}
        rescue ArgumentError, CSV::MalformedCSVError
          return nil
        end

      data = nil
      if is_postcode_data
        data = geography_service.uris_for_postcodes(uri_candidates)
        data.merge({ geography_type: 'http://opendatacommunities.org/def/geography#LSOA' })
      else
        data = geography_service.uris_and_geography_type_for_gss_codes(uri_candidates)
      end

      data
    end

    # def crumbs
    #   initialize_empty_crumbtrail
    #   prepend_crumb(DclgStatsSelector.stats_selector_display_name, new_selector_path)
    # end

    def invalid_upload
      flash.now[:error] = 'The uploaded file did not contain valid CSV data, please check and try again.'
      render :new, status: :bad_request
    end

    def mixed_gss_codes
      flash.now[:error] = 'The uploaded file should contain GSS codes at either LSOA or Local Authority level.'
      render :new, status: :bad_request
    end

    def too_many_gss_codes
      flash.now[:error] = 'The uploaded file contains more than 500 GSS codes, please reduce its size and try again.'
      render :new, status: :bad_request
    end

    def no_file_uploaded
      flash.now[:error] = 'Please provide a valid .csv or .txt file'
      render :new, status: :bad_request
    end

    def redirect_if_finished
      redirect_to selector_path(@selector) if @selector.finished
    end

    def redirect_unless_finished
      redirect_to edit_selector_path(@selector) unless @selector.finished
    end
  end
end

app/helpers/dclg_stats_selector/fragments_helper.rb
module DclgStatsSelector
  module FragmentsHelper
    def dom_id_for_dimension_value(dimension_value, prefix=nil)
      uri_string = dimension_value[:label].downcase.gsub(' ', '-')
      prefix.blank? ? uri_string : "#{prefix}-#{uri_string}"
    end

    def column_count(dimensions)
      count = 1
      dimensions.each do |dimension|
        count = count * dimension.values.size
      end
      count
    end

    def group_datasets_by_theme(datasets, themes)
      grouped_datasets = datasets.group_by do |dataset|
        theme = themes.find {|t| t.uri == dataset.theme}
        theme.label
      end

      grouped_datasets.keys.each do |label|
        grouped_datasets[label] = grouped_datasets[label].map{ |dataset| [dataset.title, dataset.uri.to_s] }
      end

      grouped_datasets
    end

    def options_for_select_from_tree(tree)
      # build up a hash containing group names (>-separated folder paths)
      options = {}
      tree.each_leaf do |node|        
        option = [node.content[:label], node.name] # label, URI
        opt_group = node.parentage.reverse.map{|n| n.content[:label]}.join(' > ')
        options[opt_group] ||= []
        options[opt_group] << option
        options
      end
      # now reduce our sensible hash to the grouped_options_for_select format
      options_as_array = options.reduce([]) do |memo, (key, value)|
        memo << [key, value]
      end
      grouped_options_for_select(options_as_array)
    end

    def choice_of_columns_available?(dimensions)
      !(dimensions.one? && dimensions.first.values.one?)
    end

  end
end

app/helpers/dclg_stats_selector/selectors_helper.rb
module DclgStatsSelector
  module SelectorsHelper
    def dom_class_for_fragment(header_column)
      "fragment-#{header_column.fragment_code}"
    end
  
    def row_count(num_rows, max_shown)
      if (num_rows==1)
        return "Previewing the only row"
      end

      if (num_rows>max_shown)
        return "Previewing <strong>#{max_shown}</strong> of <strong>#{num_rows}</strong> rows"
      else
        return "Previewing #{num_rows} of #{num_rows} rows"
      end
    end

  end
end

app/views/dclg_stats_selector/fragments/_form.html.haml
= row do
	.pmd_box_full
		.spin(style="display: none;")
			(preparing data)
			= image_tag 'publish_my_data/dclg_stats_selector/spinner.gif'

#build-fragment
	= row do
		.pmd_box_full
			.predicate Source Dataset
			%strong
				= @dataset.title
			= link_to '(change dataset)', datasets_selector_fragments_path(@selector), id: 'pick-again', remote: true

	= form_tag selector_fragments_path(@selector), id: 'bf' do
		= hidden_field_tag :dataset_uri, @dataset.uri
		- @dimensions.each do |dimension|
			%div{'id' => dimension.uri.parameterize}
				= hidden_field_tag "dataset_dimensions[#{dimension.uri}]", '', class: 'selected-values'
				= hidden_field_tag "all_dataset_dimensions[#{dimension.uri}]", dimension.values.map{|v| v[:uri]}.join(', ')

		- if choice_of_columns_available?(@dimensions)
			= row do
				.pmd_box_full{style:"margin-top:24px;"}
					.predicate Selected data
					%p#no-filters
						%em All possible combinations of dataset dimension are currently selected.
					#filters(style="display: none;")
						%p Adding data which matches
						#filter-lists{style:"padding: 10px;", class:'clearfix'}
							- @dimensions.each do |dimension|
								.dimension{style:'float:left; padding: 0 10px 10px 10px; margin-left:12px; width:25%;'}
									%h5
										= dimension.label
									%em.all-values
										Any
										/= dimension.label.pluralize
									%ul(style="display: none;")
										/%li.dimension-label= dimension.label
										- dimension.values.each do |dimension_value|
											%li{'id' => dom_id_for_dimension_value(dimension_value, 'filter'), 'style' => 'display: none;'}
												= link_to '#', class: 'remove-dimension-value' do
													= dimension_value[:label]
			= row do
				.pmd_box_full
					#filter-options{style:"background: #f8f8f8; padding: 10px;", class:'clearfix'}
						%p
							To refine your selection, choose which columns you'd like to add to your spreadsheet:
						#dimensions
							- @dimensions.each do |dimension|
								.dimension{style:'float:left; padding:12px; margin-left:12px;  width:25%;'}
									%h5
										= dimension.label
									%ul
										- dimension.values.each do |dimension_value|
											%li{'id' => dom_id_for_dimension_value(dimension_value)}
												= link_to dimension_value[:label], '#', 'data-uri' =>  dimension_value[:uri], 'data-dimension' => dimension.uri.parameterize, 'class' => 'dimension-value'
		- else
			= row do
				.pmd_box_full{style:"margin-top:24px;"}
					.predicate Selected data
					%p
						The selected dataset contains has one dimension of data and will add one column.
		= row do
			.pmd_box_full
				.submit.primary
					- label = "#{column_count(@dimensions).to_s} " + (column_count(@dimensions) == 1 ? "column" : "columns")
					= submit_tag "Add #{label}", id: 'submit-fragment', class:'btn mini'

:javascript
	var addValueWithAnchor = function(anchor) {
		var uri = anchor.attr('data-uri'),
				el = $('#'+anchor.attr('data-dimension')),
				input = el.find('input.selected-values'),
				dimensionValues;

		if (input.val().length == 0) {
			dimensionValues = [uri];
		} else {
			dimensionValues = input.val().split(', ');
			dimensionValues.push(uri);
		}
		input.val(dimensionValues.join(', '));
	},
	removeValueWithAnchor = function(anchor) {
		var uri = anchor.attr('data-uri'),
				el = $('#'+anchor.attr('data-dimension')),
				input = el.find('input.selected-values'),
				dimensionValues = input.val().split(', '),
				idx;

		idx = dimensionValues.indexOf(uri);
		dimensionValues.splice(idx, 1);
		input.val(dimensionValues.join(', '));
	},
	calculateColumnCount = function() {
		var total = 1,
				dimCount,
				colPlural;

		$('#filter-lists ul').each(function(idx) {
			var ul = $(this);

			if (ul.is(':hidden')) {
				// all values
				dimCount = $('#dimensions .dimension').eq(idx).find('li').size();
			} else  {
				// selected values
				dimCount = ul.find('li:visible').not('.dimension-label').size();
			}
			total = total * dimCount;
		});
		colPlural = (total == 1) ? 'column' : 'columns';
		$('input#submit-fragment').val('Add ' + total + ' ' + colPlural + ' of data');
	}

	$('a.dimension-value').click(function(e) {
		e.preventDefault();
		var filterOption = $(this).parent(),
				filter = $('#filter-' + filterOption.attr('id')),
				filterList = filter.parent();

		filterOption.hide();
		filter.show();
		if (filterList.is(':hidden')) {
			filterList.show();
			filterList.siblings('.all-values').hide();

			if ($('#filters').is(':hidden')) {
				$('#filters').show();
				$('#no-filters').hide();
			}
		}

		addValueWithAnchor($(this));
		calculateColumnCount();
	});

	$('a.remove-dimension-value').click(function(e) {
		e.preventDefault();

		var filter = $(this).parent(),
				filterOption = $('#' + filter.attr('id').replace('filter-', '')),
				filterList = filter.parent(),
				anchor;

		filter.hide();
		filterOption.show();

		if (!filter.siblings().not('.dimension-label').is(':visible')) {
			filterList.hide();
			filterList.siblings('.all-values').show();

			if (!$('#filter-lists .dimension ul').is(':visible')) {
				$('#filters').hide();
				$('#no-filters').show();
			}
		}

		anchor = filterOption.find('a');
		removeValueWithAnchor(anchor);
		calculateColumnCount();
	});

	$('#submit-fragment').click(function() {
		$('.spin').show();
		$('#bf').submit();
	});
	$('#pick-again').click(function() {
		$('.spin').show();
		$('#build-fragment').hide();
	});

app/views/dclg_stats_selector/fragments/datasets.html.haml
= row do
	.pmd_box_full
		#select-dataset
			.predicate Source dataset
			= form_tag new_selector_fragment_path(@selector), id: 'nsf', method: :get, remote: true do
				= select_tag :dataset_uri, options_for_select_from_tree(@tree)
				= submit_tag 'Choose this dataset', class: 'btn mini', id: 'select-dataset-button'
				.spin(style="display: none;")
					= image_tag 'publish_my_data/dclg_stats_selector/spinner.gif'

			:javascript
				$('#select-dataset-button').click(function() {
					$('.spin').show();
					$('#nsf').submit();
				});

app/views/dclg_stats_selector/fragments/datasets.js.haml
$('#add-data').html("#{ escape_javascript render(template:'dclg_stats_selector/fragments/datasets.html') }");

app/views/dclg_stats_selector/fragments/new.js.haml
$('#add-data').html("#{ escape_javascript render(partial: 'form') }");